apiVersion: v1
kind: Service
metadata:
  name: simplespringbootproservice
spec:
  selector:
    app: simplespringbootpro
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer

